package com.zuodexin.po;

import com.zuodexin.po.itf.Refreshable;

// Generated 2016-5-27 11:22:51 by Hibernate Tools 4.0.0

/**
 * Hire generated by hbm2java
 */
public class Hire implements java.io.Serializable,Refreshable {

	private int id;
	private Institute institute;
	private Professor professor;

	public Hire() {
	}

	public Hire(int id, Institute institute, Professor professor) {
		this.id = id;
		this.institute = institute;
		this.professor = professor;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Institute getInstitute() {
		return this.institute;
	}

	public void setInstitute(Institute institute) {
		this.institute = institute;
	}

	public Professor getProfessor() {
		return this.professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}

}
