package com.zuodexin.po;

// Generated 2016-5-27 11:22:51 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import com.zuodexin.po.itf.Refreshable;

/**
 * Institute generated by hbm2java
 */
public class Institute implements java.io.Serializable ,Refreshable{

	private int id;
	private String name;
	private Set<Hire> hires = new HashSet<Hire>(0);
	private Set<Course> courses = new HashSet<Course>(0);
	private Set<Professor> professors = new HashSet<Professor>(0);

	public Institute() {
	}

	public Institute(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Institute(int id, String name, Set<Hire> hires, Set<Course> courses,
			Set<Professor> professors) {
		this.id = id;
		this.name = name;
		this.hires = hires;
		this.courses = courses;
		this.professors = professors;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Hire> getHires() {
		return this.hires;
	}

	public void setHires(Set<Hire> hires) {
		this.hires = hires;
	}

	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

	public Set<Professor> getProfessors() {
		return this.professors;
	}

	public void setProfessors(Set<Professor> professors) {
		this.professors = professors;
	}

}
