package com.zuodexin.po;

// Generated 2016-5-27 11:22:51 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import com.zuodexin.po.itf.Refreshable;

/**
 * Schoolclass generated by hbm2java
 */
public class Schoolclass implements java.io.Serializable ,Refreshable{

	private int id;
	private Course course;
	private String info;
	private Set<TeachClass> teachClasses = new HashSet<TeachClass>(0);
	private Set<JionClass> jionClasses = new HashSet<JionClass>(0);

	public Schoolclass() {
	}

	public Schoolclass(int id, Course course) {
		this.id = id;
		this.course = course;
	}

	public Schoolclass(int id, Course course, String info,
			Set<TeachClass> teachClasses, Set<JionClass> jionClasses) {
		this.id = id;
		this.course = course;
		this.info = info;
		this.teachClasses = teachClasses;
		this.jionClasses = jionClasses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Set<TeachClass> getTeachClasses() {
		return this.teachClasses;
	}

	public void setTeachClasses(Set<TeachClass> teachClasses) {
		this.teachClasses = teachClasses;
	}

	public Set<JionClass> getJionClasses() {
		return this.jionClasses;
	}

	public void setJionClasses(Set<JionClass> jionClasses) {
		this.jionClasses = jionClasses;
	}

}
