package com.zuodexin.po;

// Generated 2016-6-2 11:21:52 by Hibernate Tools 4.0.0

/**
 * State generated by hbm2java
 */
public class State implements java.io.Serializable {

	private int id;
	private String name;
	private boolean canSelectCourse;
	private boolean canTeachClass;
	private boolean canGaveGrade;
	private boolean active;

	public State() {
	}

	public State(int id, String name, boolean canSelectCourse,
			boolean canTeachClass, boolean canGaveGrade, boolean active) {
		this.id = id;
		this.name = name;
		this.canSelectCourse = canSelectCourse;
		this.canTeachClass = canTeachClass;
		this.canGaveGrade = canGaveGrade;
		this.active = active;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isCanSelectCourse() {
		return this.canSelectCourse;
	}

	public void setCanSelectCourse(boolean canSelectCourse) {
		this.canSelectCourse = canSelectCourse;
	}

	public boolean isCanTeachClass() {
		return this.canTeachClass;
	}

	public void setCanTeachClass(boolean canTeachClass) {
		this.canTeachClass = canTeachClass;
	}

	public boolean isCanGaveGrade() {
		return this.canGaveGrade;
	}

	public void setCanGaveGrade(boolean canGaveGrade) {
		this.canGaveGrade = canGaveGrade;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
