package com.zuodexin.po;

import com.zuodexin.po.itf.Refreshable;

// Generated 2016-5-27 11:22:51 by Hibernate Tools 4.0.0

/**
 * TeachClass generated by hbm2java
 */
public class TeachClass implements java.io.Serializable ,Refreshable{

	private int id;
	private Professor professor;
	private Schoolclass schoolclass;

	public TeachClass() {
	}

	public TeachClass(int id, Professor professor, Schoolclass schoolclass) {
		this.id = id;
		this.professor = professor;
		this.schoolclass = schoolclass;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Professor getProfessor() {
		return this.professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}

	public Schoolclass getSchoolclass() {
		return this.schoolclass;
	}

	public void setSchoolclass(Schoolclass schoolclass) {
		this.schoolclass = schoolclass;
	}

}
